### ISSUE TITLE
More things for your vim setup

### ISSUE THREAD

**Issue by gLENTNER** [DanielAndreasen/vim-files#1]
Given that you seem to be interested in 'jedi' stuff in vim, you should add autoclose.vim and acp.vim to your repo.

-[autoclose](https://github.com/Townk/vim-autoclose)
-[autocomplete](http://www.vim.org/scripts/script.php?script_id=1879)

These auto close {},[],(),"",'' with same-character escaping and auto-complete of words, functions, variables in your environment with all the power of an IDE but the speed of VIM. They have transformed my workflow and I thought you might be interested.

**Comment by DanielAndreasen** [comment]
Hi.
Thanks for the suggestions. As of for now, I haven't updated this repository for a long time, and a lot have happened since last time. For autocompletion I use [neocomplete](https://github.com/Shougo/neocomplete.vim). However, the autoclose plugin seems nice.
